name: Snyk run test and call python script
permissions:
  contents: read
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          ref: feature-decompose-py
    - uses: actions/checkout@v4
      with: 
        repository: bgarlow/github-issue
        ref: main
    - uses: snyk/actions/setup@master
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - #name: Snyk test
      working-directory: ./01-Login
      continue-on-error: true
      run: snyk test --json > vuln.json #--severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install python
    - name: install requests
      run: python -m pip install requests
    - name: create github issue
      working-directory: .
      run: python snykgithubissue.py 01-Login/vuln.json
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      