name: Snyk example 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Snyk test
      working-directory: ./01-Login
      continue-on-error: true
      # run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install python
    - name: execute py script
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} python test.py